In [3]:
# Q1)
import numpy as np
arr = np.array([10,20,30,40,50])
print("Original Array: " , arr)
print("Adding 2 in all the elements: ", arr+2)
print("Multiplying 3 with all the elements: ", arr*3)
print("Divide every element by 2: ", arr/2)

Original Array:  [10 20 30 40 50]
Adding 2 in all the elements:  [12 22 32 42 52]
Multiplying 3 with all the elements:  [ 30  60  90 120 150]
Divide every element by 2:  [ 5. 10. 15. 20. 25.]


In [4]:
# Q2) a)
import numpy as np
arr = np.array([1,2,3,6,4,5])
print("Original Array: ", arr)
print("Reversed Array: ", arr[::-1])

Original Array:  [1 2 3 6 4 5]
Reversed Array:  [5 4 6 3 2 1]


In [6]:
# Q2) b)
# i)
x = np.array([1,2,3,4,5,1,2,1,1,1])
values, counts = np.unique(x, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(x == most_frequent)[0]

print("\nFor x:")
print("Most frequent value:", most_frequent)
print("Indices:", indices)
# ii)
y = np.array([1,1,1,2,3,4,2,4,3,3])
values, counts = np.unique(x, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(x == most_frequent)[0]

print("\nFor x:")
print("Most frequent value:", most_frequent)
print("Indices:", indices)


For x:
Most frequent value: 1
Indices: [0 5 7 8 9]

For x:
Most frequent value: 1
Indices: [0 5 7 8 9]


In [11]:
# Q3) 
arr = np.array([[10,20,30], 
               [40,50,60], 
               [70,80,90]])
print(int(arr[0, 1]))
print(int(arr[2, 0]))


20
70


In [12]:
# Q4)
import numpy as np
Dikshit = np.linspace(10, 100, 25)
print("Array:", Dikshit)
print("Dimensions:", Dikshit.ndim)
print("Shape:", Dikshit.shape)
print("Total elements:", Dikshit.size)
print("Data type:", Dikshit.dtype)
print("Total bytes:", Dikshit.nbytes)
Dikshit_transpose = Dikshit.reshape(25, 1)
print("Transpose using reshape():")
print(Dikshit_transpose)
print("Transpose using T:")
print(Dikshit.T)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose using reshape():
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [13]:
# Q5)
ucs420_Dikshit = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35])
print("Original Array:")
print(ucs420_Dikshit)
print("Mean:", np.mean(ucs420_Dikshit))
print("Median:", np.median(ucs420_Dikshit))
print("Maximum:", np.max(ucs420_Dikshit))
print("Minimum:", np.min(ucs420_Dikshit))
print("Unique elements:", np.unique(ucs420_Dikshit))
reshaped_ucs420_Dikshit = ucs420_Dikshit.reshape(4, 3)
print("\nReshaped Array (4 x 3):")
print(reshaped_ucs420_Dikshit)
resized_ucs420_Dikshit = np.resize(ucs420_Dikshit, (2, 3))
print("\nResized Array (2 x 3):")
print(resized_ucs420_Dikshit)

Original Array:
[10 20 30 40 50 60 70 80 90 15 20 35]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4 x 3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized Array (2 x 3):
[[10 20 30]
 [40 50 60]]
