In [1]:
#Q1)
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

# a. Add 2°C to every reading using vectorization
corrected_temperature = temperature + 2
print("Corrected temperatures:", corrected_temperature)

# b. Convert Celsius to Fahrenheit
fahrenheit = (9/5) * corrected_temperature + 32
print("Temperatures in Fahrenheit:", fahrenheit)

# c. Identify readings greater than 32°C
above_32 = corrected_temperature[corrected_temperature > 32]
print("Readings greater than 32°C:", above_32)

# d. Count readings exceeding 32°C
count = np.sum(corrected_temperature > 32)
print("Number of readings greater than 32°C:", count)

Corrected temperatures: [27 30 33 37 40 29 35 42]
Temperatures in Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Readings greater than 32°C: [33 37 40 35 42]
Number of readings greater than 32°C: 5


In [2]:
#Q2)
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

# a. Total steps
total_steps = np.sum(steps)
print("Total steps:", total_steps)

# b. Mean number of steps
mean_steps = np.mean(steps)
print("Mean steps:", mean_steps)

# c. Maximum and minimum values
maximum = np.max(steps)
minimum = np.min(steps)

print("Maximum steps:", maximum)
print("Minimum steps:", minimum)

# d. Total steps for each day (axis=0)
day_totals = np.sum(steps, axis=0)
print("Total steps for each day:", day_totals)

# e. Total steps for each user (axis=1)
user_totals = np.sum(steps, axis=1)
print("Total steps for each user:", user_totals)

# f. Position containing maximum number of steps
max_position = np.unravel_index(np.argmax(steps), steps.shape)
print("Position of maximum value:", max_position)

Total steps: 84200
Mean steps: 7016.666666666667
Maximum steps: 9500
Minimum steps: 4500
Total steps for each day: [26500 27300 30400]
Total steps for each user: [18300 24500 14400 27000]
Position of maximum value: (np.int64(3), np.int64(2))


In [3]:
#Q3)
import numpy as np

# a. Create the original array
original = np.array([1, 2, 3, 4, 5, 6])
print("Original array:", original)


# b. Create a slice from index 1 to 4
subset = original[1:5]
print("Subset:", subset)


# c. Modify the first element of subset
subset[0] = 999

print("After modifying subset:")
print("Original:", original)
print("Subset:", subset)


# d. Create another slice using copy()
copied = original[1:5].copy()

# Modify first element of copied array
copied[0] = 500

print("\nAfter modifying copied array:")
print("Original:", original)
print("Copied:", copied)


# e. Create numbers from 1 to 12 and reshape into 3x4
matrix = np.arange(1, 13).reshape(3, 4)

print("\n3 x 4 Matrix:")
print(matrix)


# f. Indexing and slicing

# First row
first_row = matrix[0]
print("\nFirst row:", first_row)

# Last row
last_row = matrix[-1]
print("Last row:", last_row)

# Second column
second_column = matrix[:, 1]
print("Second column:", second_column)

# Rows 1-2 and columns 2-3
selected_elements = matrix[1:3, 2:4]
print("Rows 1-2 and columns 2-3:")
print(selected_elements)


# g. Flatten using flatten() and ravel()
flattened = matrix.flatten()
raveled = matrix.ravel()

print("\nUsing flatten():", flattened)
print("Using ravel():", raveled)


# h. Modify ravel() array
raveled[0] = 1000

print("\nAfter modifying ravel:")
print("Ravel:", raveled)
print("Original matrix:")
print(matrix)


# i. Modify flatten() array
flattened[1] = 2000

print("\nAfter modifying flatten:")
print("Flatten:", flattened)
print("Original matrix:")
print(matrix)


# j. Display array properties
print("\nArray properties:")
print("Shape:", matrix.shape)
print("Number of dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

Original array: [1 2 3 4 5 6]
Subset: [2 3 4 5]
After modifying subset:
Original: [  1 999   3   4   5   6]
Subset: [999   3   4   5]

After modifying copied array:
Original: [  1 999   3   4   5   6]
Copied: [500   3   4   5]

3 x 4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2 and columns 2-3:
[[ 7  8]
 [11 12]]

Using flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
Using ravel(): [ 1  2  3  4  5  6  7  8  9 10 11 12]

After modifying ravel:
Ravel: [1000    2    3    4    5    6    7    8    9   10   11   12]
Original matrix:
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]

After modifying flatten:
Flatten: [   1 2000    3    4    5    6    7    8    9   10   11   12]
Original matrix:
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]

Array properties:
Shape: (3, 4)
Number of dimensions: 2
Size: 12
Data type: int64


In [4]:
#Q4)
import numpy as np

# Given data
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])


# a. Display shape and dimensions
print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)


# b. Transpose of X
X_transpose = X.T

print("\nTranspose of X:")
print(X_transpose)

print("\nExplanation:")
print("The transpose converts rows into columns and columns into rows.")


# c. Calculate X.T @ X
XtX = X.T @ X

print("\nX.T @ X:")
print(XtX)


# d. Calculate matrix inverse
XtX_inverse = np.linalg.inv(XtX)

print("\nInverse of X.T @ X:")
print(XtX_inverse)


# e. Calculate OLS coefficients
beta = XtX_inverse @ X.T @ y

print("\nOLS coefficients:")
print(beta)


# f. Interpretation
print("\nCoefficients:")
print("Sleep coefficient:", beta[0])
print("Activity coefficient:", beta[1])
print("Stress coefficient:", beta[2])


# g. Prediction for a new user
new_user = np.array([5, 40, 7])

predicted_score = new_user @ beta

print("\nPredicted assistance score:", predicted_score)

Shape of X: (4, 3)
Dimensions of X: 2

Transpose of X:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]

Explanation:
The transpose converts rows into columns and columns into rows.

X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]

Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

OLS coefficients:
[-0.15921454  0.14083853 10.06302242]

Coefficients:
Sleep coefficient: -0.1592145415946895
Activity coefficient: 0.14083852991906243
Stress coefficient: 10.063022422714587

Predicted assistance score: 75.27862544779117
